version: 2.23.1

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
#    volumes:
#      - .:/app
    environment:
      FLASK_DEBUG: "true"
  mongo:
    image: mongo
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example