version: 2.23.1

services:
  web-server:
    build: .
    ports:
      - "8000:8000"
    container_name: web-server
    restart: unless-stopped
    depends_on:
      - mongo
#    volumes:
#      - .:/app
    environment:
      - FLASK_DEBUG="true"
      - MONGO_URL=mongodb://mongo:27017
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
