services:
  rami-web-server:
    build:
      context: .
    ports:
      - "8001:8000"
    container_name: web-server
    restart: unless-stopped
    env_file: ./stages/${RAMI_STAGE}/.env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27018:27017"
    env_file: ./stages/${RAMI_STAGE}/.env
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
