name: pre-commit checks on changed files
on: [push, pull_request]
jobs:
  run_pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install pre-commit
      - run: |
          pre-commit run --from-ref origin/master --to-ref HEAD
