name: Build and Push Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Set Docker tag env var for master
        if: github.ref == 'refs/heads/master'
        run: |
          echo "DOCKER_TAG_NAME=latest" >> $GITHUB_ENV
          docker tag ghcr.io/${{ github.repository_owner }}/rami:${{ steps.extract_branch.outputs.branch }} ghcr.io/${{ github.repository_owner }}/rami:${{ env.DOCKER_TAG_NAME }}

      - name: Set Docker tag env var for branch
        if: github.ref != 'refs/heads/master'
        run: echo "DOCKER_TAG_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/rami:${{ env.DOCKER_TAG_NAME }} .

      - name: Push master as latest
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/rami:${{ env.DOCKER_TAG_NAME }}
