name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Fetch branches
      run: git fetch origin master
    - name: Compare changes against main
      run: git diff origin/master...HEAD
    - name: Get Changed Python Files
      id: changes
      run: |
        echo $(git diff --name-only origin/master...HEAD -- '*.py' | tr '\n' ' ')
        echo "::set-output name=files::$(git diff --name-only origin/master...HEAD -- '*.py' | tr '\n' ' ')"
    - name: Analysing the changed files with pylint
      run: |
        if [ -n "${{ steps.changes.outputs.files }}" ]; then
          echo "Running pylint on changed files: ${{ steps.changes.outputs.files }}"
          pylint ${{ steps.changes.outputs.files }}
        else
          echo "No Python files changed."
        fi
        
